# name: py312_1
name: base
dependencies:
  - python=3.12
  - pip
  - duckdb
  - pyarrow
  - pandas
  - uuid
  - re
  - kiwipiepy # Kiwi의 공식 pip 패키지 이름
  - mecab-python3
  - beautifulsoup4
  - logging
  - os
  - argparse
  - platform
  - json
  - lxml
  - datetime
  - poetry
  - poethepoet
  - concurrent.futures
  - numpy
