# name: py312_1
channels:
  - defaults
  - conda-forge
  # - huggingface
  # - pytorch
  # - nvidia
dependencies:
  - python>=3.10
  - pip
  - duckdb
  - pyarrow
  # - pandas
  ## Pandas 2.2.2 is now compatible with numpy 2.0   https://pandas.pydata.org/docs/whatsnew/v2.2.2.html
  - pandas>=2.2.2
  - uuid
  - re
  # - kiwipiepy # Kiwi의 공식 pip 패키지 이름
  # - mecab-python3
  - beautifulsoup4
  - logging
  - os
  - argparse
  - platform
  - json
  - lxml
  - datetime
